### ISSUE TITLE
Where to test a function declared for devise to use?

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#36]
I created this function based on the [docs](https://github.com/plataformatec/devise/wiki/How-To:-redirect-to-a-specific-page-on-successful-sign-in):
https://github.com/felipefreitag/pangeas/blob/1ad94fe81960df8d748533eaf13d0469b6bd0d72/app/controllers/application_controller.rb#L43
Now we have a static home page (under construction) and when the user logs in he is redirected to sections#index o/
In what file should I test this function?

**Comment by danielweinmann** [comment]
I think a good approach would be to make a `requests/sections/index_spec.rb` context where you sign in and check for the redirect ;)

**Comment by felipefreitag** [comment]
Ok... I tried using the same `sign_in` call we used in other tests but it isn't redirecting. I'll explore it further later.

**Comment by danielweinmann** [comment]
What I'm suggesting is that you do a `POST /users/sign_in` with correct params and check for a redirect, as if you were testing if the devise's endpoints work.

Actually, it is probably better to have a different file for that: `specs/requests/users/sign_in_spec.rb`. You don't need to test anything but the redirect, though, since devise itself is very well tested o/
