### ISSUE TITLE
Renewed/expired subscriptions

### ISSUE THREAD

**Issue by felipefreitag** [felipefreitag/pangeas#63]
Subscriptions activation is working o/

Now we have to create the flow of renewing/expiring them.

To renew, we could use the same `subscriptions/activate` (since it's already listening for `subscription.renewed` hook) and, if the subscription is already active, just update the `activated_at` field.

To suspend: [Iugu works](https://support.iugu.com/hc/pt-br/articles/213159443-Assinaturas-par%C3%A2metros-suspended-e-active-como-funciona-) with two boolean parameters: `active` and `suspended`, more details on the link.

There is a webhook we could listen: [subscription.expired] (https://dev.iugu.com/v1.0/docs/fluxo-recorrencia). Use it to update the subscriptions instead of calculating expiration dates within the system, Iugu already does that.

There is also the webhook `subscription.suspended`, but that means it won't be renewed anymore - it could still be active until the current cycle expires. I think we only need to track the expired ones...

@danielweinmann I'll need help on this one ;)

**Comment by danielweinmann** [comment]
Great!

Let's do it but (maybe immediately) after our launch. I think we can schedule a meeting with Vini and Nati for next week, maybe Thursday morning, to present them with what we have and to enable them to start registering things on Adminium. They will take some time on that, so that's already our bottleneck ;)

What do you think? Can you schedule with them?

**Comment by felipefreitag** [comment]
The client will do this control manually for now.
